### ISSUE TITLE
Wrong line breaks for html elements

### ISSUE THREAD

**Issue by mispp** [zed-extensions/svelte#11]
Current situation

```
<label
    for="username"
    class="block mb-2 text-sm font-medium text-gray-900"
    >Your username</label
>
```

Wanted situation:

```
<label
    for="username"
    class="block mb-2 text-sm font-medium text-gray-900"
>
    Your username
</label>
```

**Comment by jhwz** [comment]
This is the desired behaviour, the former preserves preserves having no whitespace before/after the text. If you always formatted to the latter example then the HTML would always insert a space afterwards.

**Comment by notpeter** [comment]
Zed does not directly make choices about how to format a file that is handled by other upstream dependencies.

Zed svelte extension currently uses prettier (and `prettier-plugin-svelte`) for formatting, but Zed can also be configured to use a language server or an external process for formatting.   If you have an existing cli tool that formats the way you like we can absolutely integrate with that.

Docs: https://zed.dev/docs/configuring-zed#formatter

Thanks!
